language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - "cp hfa/settings.example.py hfa/settings.py"
  - "./manage.py syncdb --noinput"
  - "pip install -r dependencies.txt"
script: "./manage.py test diary"
